Add Lighthouse github action step

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -1,9 +1,34 @@
-name: Push Container to Heroku
+name: Continuous Delivery
 
 on: [push]
 
 jobs:
+  lhci:
+    name: Lighthouse CI
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version: [14.x]
+    steps:
+      - uses: actions/checkout@v1
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v1
+        with:
+          node-version: ${{ matrix.node-version }}
+      - name: Install packages
+        run: yarn
+      - name: Build app
+        run: yarn build
+      - name: Start app
+        run: yarn start:noport
+      - name: Audit with Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+
   build:
+    name: Build & Deploy
+    needs: [smoke-test, lhci]
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
